### ISSUE TITLE
开启opencv报错，如下

### ISSUE THREAD

**Issue by gitchenjh** [uglyer/wechat_jump_ai_kotlin#5]
C:\server\java\jdk1.8.0_144\bin\java -Djava.library.path=D:\gitresp\wechat_jump_ai_kotlin\lib\x64 -javaagent:C:\server\idea\lib\idea_rt.jar=55892:C:\server\idea\bin -Dfile.encoding=UTF-8 -classpath C:\server\java\jdk1.8.0_144\jre\lib\charsets.jar;C:\server\java\jdk1.8.0_144\jre\lib\deploy.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\access-bridge-64.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\cldrdata.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\dnsns.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\jaccess.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\jfxrt.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\localedata.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\nashorn.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\sunec.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\sunjce_provider.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\sunmscapi.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\sunpkcs11.jar;C:\server\java\jdk1.8.0_144\jre\lib\ext\zipfs.jar;C:\server\java\jdk1.8.0_144\jre\lib\javaws.jar;C:\server\java\jdk1.8.0_144\jre\lib\jce.jar;C:\server\java\jdk1.8.0_144\jre\lib\jfr.jar;C:\server\java\jdk1.8.0_144\jre\lib\jfxswt.jar;C:\server\java\jdk1.8.0_144\jre\lib\jsse.jar;C:\server\java\jdk1.8.0_144\jre\lib\management-agent.jar;C:\server\java\jdk1.8.0_144\jre\lib\plugin.jar;C:\server\java\jdk1.8.0_144\jre\lib\resources.jar;C:\server\java\jdk1.8.0_144\jre\lib\rt.jar;D:\gitresp\wechat_jump_ai_kotlin\build\production\wechat_jump_ai_kotlin;D:\gitresp\wechat_jump_ai_kotlin\lib\kotlin-stdlib.jar;D:\gitresp\wechat_jump_ai_kotlin\lib\kotlin-reflect.jar;D:\gitresp\wechat_jump_ai_kotlin\lib\kotlin-test.jar;D:\gitresp\wechat_jump_ai_kotlin\lib\kotlin-stdlib-jdk7.jar;D:\gitresp\wechat_jump_ai_kotlin\lib\kotlin-stdlib-jdk8.jar;D:\gitresp\wechat_jump_ai_kotlin\lib\opencv-340.jar App.MainKt
bgColor R:214 G:218 B:229
OpenCV Error: Assertion failed ((depth == 0 || depth == 5) && type == _templ.type() && _img.dims() <= 2) in cv::matchTemplate, file C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\templmatch.cpp, line 1102
Exception in thread "AWT-EventQueue-0" CvException [org.opencv.core.CvException: cv::Exception: C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\templmatch.cpp:1102: error: (-215) (depth == 0 || depth == 5) && type == _templ.type() && _img.dims() <= 2 in function cv::matchTemplate
]
	at org.opencv.imgproc.Imgproc.matchTemplate_1(Native Method)
	at org.opencv.imgproc.Imgproc.matchTemplate(Imgproc.java:2555)
	at App.AIKt.runAI(AI.kt:85)
	at App.MainKt$main$jPanel$1.paintComponent(Main.kt:34)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by uglyer** [comment]
START_LOCATION 路径配置了吗？

**Comment by gitchenjh** [comment]
package App

/**
 * adb所在位置
 */
//val ADB_PATH = "/Users/iosdevlog/Library/Android/sdk/platform-tools/adb"
//val ADB_PATH = "D:\\soft\\adb\\adb.exe"
val ADB_PATH = "E:\\zuk\\adb\\adb.exe"

/**
 * 截屏文件所在位置
 */
val SCREENSHOT_LOCATION = "E:\\zuk\\s.png"
val SCREENSHOT_LOCATION_OUT = "E:\\zuk\\s_out.png"
val SCREENSHOT_LOCATION_OUT_DIR = "E:\\zuk\\out\\"

/**
 * 起始图查找位置
 */
val START_LOCATION = "E:\\zuk\\start.png"

/**
 * 是否使用opencv识别
 */
val USE_OPENCV = true

/**
 * 定时器时间,可以根据手机响应速度适当调整，单位毫秒
 */
val TIMER: Long = 5000

/**
 * 移动系数，如果跳的位置不准确，可以适当修改系数，我的手机是1080p，2.2合适.
 */
val MAGIC_NUMBER = 2.2

/**
 * 保存每次处理的截图,用于获取失败情况样本,目前版本识别没有出现失败,错误均出现在移动(点找对了,但是跳的位置不对).
 */
val IS_SAVE_HISTORY = true



配置了

**Comment by uglyer** [comment]
图片也复制到对应路径了？

**Comment by uglyer** [comment]
http://answers.opencv.org/question/53902/opencv-error-assertion-failed-scn-3-scn-4-depth-cv_8u-depth-cv_32f/

**Comment by uglyer** [comment]
参考这个的话，应该是输入图像是空的。

**Comment by gitchenjh** [comment]
是不是得单独安装opencv啊，但是我看有相应的dll文件而且调用了opencv啊

**Comment by uglyer** [comment]
可以单独安装试一下，opencv 我也不是很熟。

**Comment by gitchenjh** [comment]
debug了一下，不是空的
![qq 20171231114811](https://user-images.githubusercontent.com/24949156/34459108-83204cfe-ee20-11e7-8ce0-c634726166dd.png)

**Comment by uglyer** [comment]
templete 是不是空的。

**Comment by gitchenjh** [comment]
发现了，执行到这儿，START_LOCATION 路径的文件不存在，template参数有问题

**Comment by uglyer** [comment]
把pic下的start.png复制过去。

**Comment by gitchenjh** [comment]
刚刚解决了，多谢
